### PR TITLE
Fix semaphore access for simbicycle full state

### LINKED ISSUE #160: Thread safe member variable access in sim::Bicycle during dynamics update
Look into this at some point.

### PR DESCRIPTION
**Pull request by oliverlee**
Fixes #160.

### CODE REVIEW

File: projects/src/simbicycle.hh [hunk 1]
```diff
@@ -78,8 +78,11 @@ void Bicycle<Model, Observer>::update_dynamics(real_t roll_torque_input, real_t
 
     // The auxiliary states _must_ also be integrated at the same time as the
     // dynamic state. After the observer update, we "merge" dynamic states together.
+    chBSemWait(&m_state_sem);
+    full_state_t x = m_state_full;
```
Comment (mickvangelderen) [inline projects/src/simbicycle.hh]: `x` => `state_full_copy`

File: projects/src/simbicycle.hh [hunk 2]
```diff
@@ -78,8 +78,11 @@ void Bicycle<Model, Observer>::update_dynamics(real_t roll_torque_input, real_t
...
+    chBSemSignal(&m_state_sem);
     full_state_t state_full = m_model.integrate_full_state(
```
Comment (mickvangelderen) [inline projects/src/simbicycle.hh]: `state_full` => `state_full_next` / new / integrated
